### ISSUE TITLE
docs have broken link to telemetry

### ISSUE THREAD

**Issue by SlavaMo** [stafiprotocol/stafi-node#1]
https://docs.stafi.io/staking/validator-guide

screenshot from doc:
-----
![image](https://user-images.githubusercontent.com/56453863/86510598-cb16d900-bdf9-11ea-9800-7488f5b593e6.png)
-----

should be fixed: `https://telemetry.polkadot.io/#list/Stafi%20Testnet%20v0.1.0` -> `https://telemetry.polkadot.io/#list/Stafi%20Testnet%20Seiya`

**Comment by Tore19** [comment]
@SlavaMo  Fixed. Thanks for your reminder.
