### ISSUE TITLE
 Node compile error v0.5.2

### ISSUE THREAD

**Issue by 17621859515** [stafiprotocol/stafi-node#17]
I follow the readme.md documentation to compile the source code v0.5.2
I get this error.
This is the execution command: "cargo build --release" error
Can anyone help me with this, what dependencies am I missing?

![origin_img_v2_792feab5-5eda-41e1-9003-9fcb55043a8h](https://user-images.githubusercontent.com/69946784/188536625-0404257c-e36c-4e11-95cf-d4de65444c79.jpg)

**Comment by Tore19** [comment]
Please try rust version 1.59.0.

```
rustup install 1.59.0
rustup default 1.59.0
```

Then `cargo build --release` again.
