### ISSUE TITLE
 No space left on device" 

### ISSUE THREAD

**Issue by xhhha** [stafiprotocol/stafi-node#2]
Thread 'tokio-runtime-worker' panicked at 'Critical database eror: Custom { kind: Other, error: Error { message: "IO error: No space left on deviceWhile appending to file: /root/.local/share/stafi/chains/stafi_public_testnet/db/018706.log: No space left on device" } }', /rustc/5c1f21c3b82297671ad3ae1e8c942d2ca92e84f2/src/libstd/macros.rs:16

**Comment by stafiprotocol** [comment]
No space left on device. I think you should expand your disk size.
