### ISSUE TITLE
/root/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-sys-0.7.2/wabt/src/option-parser.cc:60:20: error: ‘CMAKE_PROJECT_VERSION’ was not declared in this scope

### ISSUE THREAD

**Issue by zhp1254** [stafiprotocol/stafi-node#4]
error: failed to run custom build command for `wabt-sys v0.7.2`

Caused by:
  process didn't exit successfully: `/data/coin/stafi/stafi-node/target/release/build/wabt-sys-2a81b5762c3d06cb/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=WABT_CXXSTDLIB
  cargo:rerun-if-env-changed=CXXSTDLIB
  running: "cmake" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-sys-0.7.2/wabt" "-DBUILD_TESTS=OFF" "-DBUILD_TOOLS=OFF" "-DCMAKE_INSTALL_PREFIX=/data/coin/stafi/stafi-node/target/release/build/wabt-sys-fa8863ef1690dcf7/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /data/coin/stafi/stafi-node/target/release/build/wabt-sys-fa8863ef1690dcf7/out/build
  running: "cmake" "--build" "." "--config" "Release" "--"
  [  1%] Building CXX object CMakeFiles/wabt.dir/src/option-parser.cc.o
  CMakeFiles/wabt.dir/build.make:686: recipe for target 'CMakeFiles/wabt.dir/src/option-parser.cc.o' failed
  CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/wabt.dir/all' failed
  Makefile:83: recipe for target 'all' failed

  --- stderr
  /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-sys-0.7.2/wabt/src/option-parser.cc: In lambda function:
  /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wabt-sys-0.7.2/wabt/src/option-parser.cc:60:20: error: ‘CMAKE_PROJECT_VERSION’ was not declared in this scope
       printf("%s\n", CMAKE_PROJECT_VERSION);

**Comment by Tore19** [comment]
Should upgrade the Cmake version. Follow this guide:
https://docs.stafi.io/validator-sv/run-a-node#compile-error
